-- 题库依赖切片：公开 ID/空串 legacy 命名空间不变；来源授权仍由 typed provider 复验。
CREATE TABLE enterprise.notebook_entries (
  tenant_id uuid NOT NULL,
  owner_id text NOT NULL,
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  session_id text NOT NULL,
  turn_id text NOT NULL DEFAULT '',
  question_id text NOT NULL,
  question text NOT NULL,
  question_type text NOT NULL DEFAULT '',
  options jsonb NOT NULL DEFAULT '{}',
  correct_answer text NOT NULL DEFAULT '',
  explanation text NOT NULL DEFAULT '',
  difficulty text NOT NULL DEFAULT '',
  user_answer text NOT NULL DEFAULT '',
  user_answer_images jsonb NOT NULL DEFAULT '[]' CHECK (jsonb_typeof(user_answer_images) = 'array'),
  source text NOT NULL DEFAULT 'deep_question' CHECK (source IN ('deep_question','book','mastery_path','immersive_reading')),
  material_id text NOT NULL DEFAULT '',
  material_title text NOT NULL DEFAULT '',
  section_id text NOT NULL DEFAULT '',
  section_title text NOT NULL DEFAULT '',
  score_trend text NOT NULL DEFAULT 'new' CHECK (score_trend IN ('new','unchanged','improved','declined')),
  is_correct boolean NOT NULL DEFAULT false,
  resolved boolean NOT NULL DEFAULT false,
  bookmarked boolean NOT NULL DEFAULT false,
  followup_session_id text NOT NULL DEFAULT '',
  ai_judgment text NOT NULL DEFAULT '',
  created_at double precision NOT NULL,
  updated_at double precision NOT NULL,
  version bigint NOT NULL DEFAULT 1 CHECK (version >= 1),
  -- book.turn_id 是 block ID；其它非空 turn 必须真实存在，不能手填 NULL 绕过。
  execution_turn_id text GENERATED ALWAYS AS
    (CASE WHEN source <> 'book' THEN nullif(turn_id,'') END) STORED,
  followup_session_ref text GENERATED ALWAYS AS (nullif(followup_session_id,'')) STORED,
  PRIMARY KEY (tenant_id,owner_id,id),
  UNIQUE (tenant_id,owner_id,session_id,turn_id,question_id),
  FOREIGN KEY (tenant_id,owner_id,session_id)
    REFERENCES enterprise.sessions(tenant_id,owner_id,id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id,owner_id,session_id,execution_turn_id)
    REFERENCES enterprise.turns(tenant_id,user_id,session_id,id),
  -- 被其它条目引用的 followup 删除明确拒绝；原 session 删除仍级联清理自身条目。
  FOREIGN KEY (tenant_id,owner_id,followup_session_ref)
    REFERENCES enterprise.sessions(tenant_id,owner_id,id)
);
CREATE TABLE enterprise.notebook_categories (
  tenant_id uuid NOT NULL,
  owner_id text NOT NULL,
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL CHECK (length(name) > 0),
  created_at double precision NOT NULL,
  version bigint NOT NULL DEFAULT 1 CHECK (version >= 1),
  -- SQLite NOCASE 仅折叠 ASCII；不要用依赖 locale 的 lower 或 Unicode casefold。
  -- 对外名称仍由 provider 使用 Python strip() 规范化后写入。
  name_key text COLLATE "C" GENERATED ALWAYS AS
    (translate(name,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')) STORED,
  PRIMARY KEY (tenant_id,owner_id,id),
  UNIQUE (tenant_id,owner_id,name_key),
  FOREIGN KEY (tenant_id,owner_id) REFERENCES enterprise.users(tenant_id,id)
);
CREATE TABLE enterprise.notebook_entry_categories (
  tenant_id uuid NOT NULL,
  owner_id text NOT NULL,
  entry_id bigint NOT NULL,
  category_id bigint NOT NULL,
  PRIMARY KEY (tenant_id,owner_id,entry_id,category_id),
  FOREIGN KEY (tenant_id,owner_id,entry_id)
    REFERENCES enterprise.notebook_entries(tenant_id,owner_id,id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id,owner_id,category_id)
    REFERENCES enterprise.notebook_categories(tenant_id,owner_id,id) ON DELETE CASCADE
);
-- scope 前缀限制个人扫描面；时间+ID 支持双向稳定游标，不依赖 offset。
CREATE INDEX notebook_entries_recent ON enterprise.notebook_entries
  (tenant_id,owner_id,created_at DESC,id DESC);
CREATE INDEX notebook_entries_session ON enterprise.notebook_entries
  (tenant_id,owner_id,session_id,created_at DESC,id DESC);
CREATE INDEX notebook_entries_material ON enterprise.notebook_entries
  (tenant_id,owner_id,source,material_id,section_id,created_at DESC,id DESC);
CREATE INDEX notebook_entries_bookmarked ON enterprise.notebook_entries
  (tenant_id,owner_id,created_at DESC,id DESC) WHERE bookmarked;
CREATE INDEX notebook_entries_execution_turn ON enterprise.notebook_entries
  (tenant_id,owner_id,session_id,execution_turn_id) WHERE execution_turn_id IS NOT NULL;
CREATE INDEX notebook_entries_followup ON enterprise.notebook_entries
  (tenant_id,owner_id,followup_session_ref) WHERE followup_session_ref IS NOT NULL;
CREATE INDEX notebook_entry_categories_category ON enterprise.notebook_entry_categories
  (tenant_id,owner_id,category_id,entry_id);
DO $$ DECLARE t text; BEGIN
  FOREACH t IN ARRAY ARRAY['notebook_entries','notebook_categories','notebook_entry_categories'] LOOP
    EXECUTE format('ALTER TABLE enterprise.%I ENABLE ROW LEVEL SECURITY',t);
    EXECUTE format('ALTER TABLE enterprise.%I FORCE ROW LEVEL SECURITY',t);
    EXECUTE format('CREATE POLICY tenant_scope ON enterprise.%I USING (tenant_id = nullif(current_setting(''app.tenant_id'',true),'''')::uuid) WITH CHECK (tenant_id = nullif(current_setting(''app.tenant_id'',true),'''')::uuid)',t);
    EXECUTE format('CREATE POLICY owner_scope ON enterprise.%I AS RESTRICTIVE USING (owner_id = nullif(current_setting(''app.user_id'',true),'''')) WITH CHECK (owner_id = nullif(current_setting(''app.user_id'',true),''''))',t);
  END LOOP;
END $$;
GRANT SELECT,INSERT,UPDATE,DELETE ON enterprise.notebook_entries,
  enterprise.notebook_categories,enterprise.notebook_entry_categories TO dt_enterprise_app;
GRANT USAGE ON SEQUENCE enterprise.notebook_entries_id_seq,
  enterprise.notebook_categories_id_seq TO dt_enterprise_app;
