-- Relocate management authorization business routines, triggers, and CHECK rules to application code.

DROP TRIGGER IF EXISTS validate_action_catalog_change ON management.action_catalog;
DROP TRIGGER IF EXISTS validate_assignment ON management.assignments;
DROP TRIGGER IF EXISTS protect_last_administrator ON management.assignments;
DROP TRIGGER IF EXISTS protect_last_administrator_principal ON management.principals;
DROP TRIGGER IF EXISTS assignment_policy_version ON management.assignments;
DROP TRIGGER IF EXISTS delegation_policy_version ON management.delegation_policies;
DROP TRIGGER IF EXISTS validate_delegation_policy ON management.delegation_policies;
DROP TRIGGER IF EXISTS role_versions_append_only ON management.role_versions;
DROP TRIGGER IF EXISTS role_actions_append_only ON management.role_actions;
DROP TRIGGER IF EXISTS audit_events_append_only ON management.audit_events;
DROP TRIGGER IF EXISTS validate_role_action ON management.role_actions;
DROP FUNCTION IF EXISTS management.validate_action_catalog_change();
DROP FUNCTION IF EXISTS management.validate_assignment();
DROP FUNCTION IF EXISTS management.protect_last_administrator();
DROP FUNCTION IF EXISTS management.protect_last_administrator_principal();
DROP FUNCTION IF EXISTS management.bump_principal_policy_version();
DROP FUNCTION IF EXISTS management.validate_delegation_policy();
DROP FUNCTION IF EXISTS management.reject_immutable_fact();
DROP FUNCTION IF EXISTS management.validate_role_action();

ALTER TABLE management."action_catalog" DROP CONSTRAINT IF EXISTS "action_catalog_allowed_scope_check";
ALTER TABLE management."action_catalog" DROP CONSTRAINT IF EXISTS "action_catalog_application_check";
ALTER TABLE management."action_catalog" DROP CONSTRAINT IF EXISTS "action_catalog_check";
ALTER TABLE management."action_catalog" DROP CONSTRAINT IF EXISTS "action_catalog_check1";
ALTER TABLE management."action_catalog" DROP CONSTRAINT IF EXISTS "action_catalog_status_check";
ALTER TABLE management."approval_requests" DROP CONSTRAINT IF EXISTS "approval_distinct_reviewer";
ALTER TABLE management."approval_requests" DROP CONSTRAINT IF EXISTS "approval_requests_application_check";
ALTER TABLE management."approval_requests" DROP CONSTRAINT IF EXISTS "approval_requests_check";
ALTER TABLE management."approval_requests" DROP CONSTRAINT IF EXISTS "approval_requests_operation_check";
ALTER TABLE management."approval_requests" DROP CONSTRAINT IF EXISTS "approval_requests_status_check";
ALTER TABLE management."assignments" DROP CONSTRAINT IF EXISTS "assignments_application_check";
ALTER TABLE management."assignments" DROP CONSTRAINT IF EXISTS "assignments_check1";
ALTER TABLE management."assignments" DROP CONSTRAINT IF EXISTS "assignments_check2";
ALTER TABLE management."assignments" DROP CONSTRAINT IF EXISTS "assignments_school_binding_version_valid";
ALTER TABLE management."assignments" DROP CONSTRAINT IF EXISTS "assignments_scope_kind_check";
ALTER TABLE management."assignments" DROP CONSTRAINT IF EXISTS "assignments_status_check";
ALTER TABLE management."audit_events" DROP CONSTRAINT IF EXISTS "audit_events_application_check";
ALTER TABLE management."audit_events" DROP CONSTRAINT IF EXISTS "audit_events_check2";
ALTER TABLE management."audit_events" DROP CONSTRAINT IF EXISTS "audit_events_result_check";
ALTER TABLE management."delegation_policies" DROP CONSTRAINT IF EXISTS "delegation_policies_application_check";
ALTER TABLE management."delegation_policies" DROP CONSTRAINT IF EXISTS "delegation_policies_check1";
ALTER TABLE management."delegation_policies" DROP CONSTRAINT IF EXISTS "delegation_policies_scope_kind_check";
ALTER TABLE management."delegation_policies" DROP CONSTRAINT IF EXISTS "delegation_policies_status_check";
ALTER TABLE management."principals" DROP CONSTRAINT IF EXISTS "principals_application_check";
ALTER TABLE management."principals" DROP CONSTRAINT IF EXISTS "principals_check";
ALTER TABLE management."principals" DROP CONSTRAINT IF EXISTS "principals_status_check";
ALTER TABLE management."role_versions" DROP CONSTRAINT IF EXISTS "role_versions_application_check";
ALTER TABLE management."role_versions" DROP CONSTRAINT IF EXISTS "role_versions_check";
ALTER TABLE management."role_versions" DROP CONSTRAINT IF EXISTS "role_versions_scope_kind_check";
