"use client";

import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import { Activity, AppWindow, BookOpenCheck, ClipboardList, LayoutDashboard, ScrollText, ShieldCheck, UsersRound, Sparkles } from "lucide-react";
import type { DisplayState } from "@deeptutor/api-contracts";
import { AdminShell, Button, ConfirmModal, DataTable, DetailGrid, Drawer, FormModal, MetricStrip, Notice, PageHead, Section, StatePanel, StatusBadge, Tabs, useLocationSearch, useSessionFilter } from "@deeptutor/admin-ui";
import { OcrServiceList, ServiceDetail, ServiceList } from "@deeptutor/service-components";
import { apps as initialApps, appServiceAccess, calls, documents, events, grants, knowledge, members, memberAppAccess, processingTasks, services, tenant } from "./fixtures";
import TmsSkills from "./TmsSkills";
import TmsAuthorization, { TmsMemberRoles, initialTmsAuth, type TmsAuthState } from "./TmsAuthorization";
import TmsSchoolActivation from "./TmsSchoolActivation";
import TmsMemberLookup from "./TmsMemberLookup";

const authRoots = new Set(["roles", "access-grants", "authz-records"]);

const navigation = (base: string) => [
  { label: "工作台", items: [{ label: "学校概览", href: base, icon: <LayoutDashboard/> }] },
  { label: "成员与权限", items: [{ label: "成员列表", href: `${base}/members`, icon: <UsersRound/> }, { label: "学校角色", href: `${base}/roles`, icon: <ShieldCheck/> }, { label: "访问关系", href: `${base}/access-grants`, icon: <AppWindow/> }, { label: "授权记录", href: `${base}/authz-records`, icon: <ScrollText/> }] },
  { label: "应用与接入", items: [{ label: "应用列表", href: `${base}/apps`, icon: <AppWindow/> }] },
  { label: "服务与配额", items: [{ label: "可用服务", href: `${base}/services`, icon: <ClipboardList/> }, { label: "配额清单", href: `${base}/quotas`, icon: <ShieldCheck/> }, { label: "Skills", href: `${base}/skills`, icon: <Sparkles/> }] },
  { label: "知识与内容", items: [{ label: "知识库列表", href: `${base}/knowledge`, icon: <BookOpenCheck/> }] },
  { label: "用量与记录", items: [{ label: "调用用量", href: `${base}/usage`, icon: <Activity/> }, { label: "管理事件", href: `${base}/events`, icon: <ScrollText/> }] },
];
function badge(value: string) {
  const tone = value.includes("失败") || value.includes("用尽") ? "bad" : value.includes("待") || value.includes("处理") || value.includes("核对") ? "warn" : "good";
  return <StatusBadge tone={tone}>{value}</StatusBadge>;
}
function title(value: string, sub?: string) { return <><span className="cell-title">{value}</span>{sub && <span className="cell-sub">{sub}</span>}</>; }
function decodeSkillId(segment: string | undefined): string | undefined {
  if (!segment) return undefined;
  try { return decodeURIComponent(segment); } catch { return undefined; }
}

function TmsPrototypeForSchool({ schoolCode }: { schoolCode: string }) {
  const base = `/tms/prototype/${encodeURIComponent(schoolCode)}`;
  const nav = navigation(base);
  const pathname = usePathname();
  const locationSearch = useLocationSearch();
  const [route, setRoute] = useState(pathname);
  const [returnRoute, setReturnRoute] = useState<string | null>(null);
  useEffect(() => { const onPopState = () => { setReturnRoute(null); setRoute(window.location.pathname); }; window.addEventListener("popstate", onPopState); return () => window.removeEventListener("popstate", onPopState); }, []);
  const inSchoolScope = route === base || route.startsWith(`${base}/`);
  const segments = route === base ? [] : inSchoolScope ? route.slice(base.length + 1).split("/").filter(Boolean) : ["invalid"];
  const root = segments[0] || "home";
  const skillId = root === "skills" ? decodeSkillId(segments[1]) : undefined;
  const go = (path: string, returning = false) => { const target = new URL(path, window.location.href); const targetSegments = target.pathname.startsWith(`${base}/`) ? target.pathname.slice(base.length + 1).split("/").filter(Boolean) : []; if (!returning) { if (targetSegments.length > 1 && (segments.length === 0 || segments.length > 1 && root !== targetSegments[0])) setReturnRoute(route); else if (targetSegments.length <= 1) setReturnRoute(null); } setFormOpen(false); setDirectoryOpen(false); setServiceFormOpen(false); setAppMemberFormOpen(false); setAccessConfirmation(null); setServiceConfirmation(null); setRetryConfirmation(null); setMessage(""); setRoute(target.pathname); if (window.location.pathname + window.location.search !== target.pathname + target.search) window.history.pushState(null, "", target.pathname + target.search); };
  const [role, setRole] = useState("admin");
  const [authScenario, setAuthScenario] = useState("active");
  const [authState, setAuthState] = useState<TmsAuthState>(initialTmsAuth);
  const [authModalOpen, setAuthModalOpen] = useState(false);
  const [scenario, setScenario] = useState("normal");
  const [method, setMethod] = useSessionFilter(`tms:${schoolCode}:quota-method`, "all");
  const [apps, setApps] = useState(initialApps);
  const [formOpen, setFormOpen] = useState(false);
  const [directoryOpen, setDirectoryOpen] = useState(false);
  const [appName, setAppName] = useState("");
  const [appOwner, setAppOwner] = useState("教务处");
  const [message, setMessage] = useState("");
  const [catalogTab, setCatalogTab] = useState("全部服务");
  const [memberAccess, setMemberAccess] = useState<Record<string, string[]>>(memberAppAccess);
  const [serviceAccess, setServiceAccess] = useState<Record<string, string[]>>(appServiceAccess);
  const [serviceFormOpen, setServiceFormOpen] = useState(false);
  const [appMemberFormOpen, setAppMemberFormOpen] = useState(false);
  const [serviceChoice, setServiceChoice] = useState("");
  const [memberChoice, setMemberChoice] = useState("");
  const [serviceConfirmation, setServiceConfirmation] = useState<{ appId: string; serviceId: string; action: "add" | "remove" } | null>(null);
  const [retryRequests, setRetryRequests] = useState<string[]>([]);
  const [retryConfirmation, setRetryConfirmation] = useState<string | null>(null);
  const [accessConfirmation, setAccessConfirmation] = useState<{ memberId: string; appId: string; action: "grant" | "revoke" } | null>(null);
  const [accessApp, setAccessApp] = useState("app-01");
  const eligibleApps = apps.filter(item => item.status === "运行中" && (serviceAccess[item.id] ?? []).some(id => services.some(service => service.id === id)));
  const viewState: DisplayState = role === "member" || scenario === "forbidden" ? "forbidden" : scenario === "loading" ? "loading" : scenario === "error" ? "error" : scenario === "empty" ? "empty" : "ready";
  const crumbs = (section: string, parent: string, detail?: string) => [{ label: "工作台", onClick: () => go(base) }, { label: section, onClick: () => go(parent) }, ...(detail ? [{ label: detail }] : [])];
  const list = <T extends { id: string }>(rows: T[], columns: { key: string; label: string; render: (row: T) => React.ReactNode }[], route: (row: T) => string, searchLabel: string) => <Section><DataTable rows={viewState === "empty" ? [] : rows} columns={columns} searchLabel={searchLabel} persistKey={`tms:${schoolCode}:${root}`} onOpen={row => go(route(row))} state={viewState}/></Section>;
  const renderContent = (segments: string[]): React.ReactNode => {
  let content: React.ReactNode;

  if (authRoots.has(root)) {
    content = <TmsAuthorization section={root as "roles" | "access-grants" | "authz-records"} selectedId={decodeSkillId(segments[1])} state={authState} onChange={setAuthState} memberAccess={memberAccess} serviceAccess={serviceAccess} onMemberAccess={(memberId, appId, add) => setMemberAccess(current => ({ ...current, [memberId]: add ? [...new Set([...(current[memberId] ?? []), appId])] : (current[memberId] ?? []).filter(id => id !== appId) }))} onServiceAccess={(appId, serviceId, add) => setServiceAccess(current => ({ ...current, [appId]: add ? [...new Set([...(current[appId] ?? []), serviceId])] : (current[appId] ?? []).filter(id => id !== serviceId) }))} onOpen={id => go(`${base}/${root}/${encodeURIComponent(id)}`)} onClose={() => go(`${base}/${root}`)} role={role}/>;
  } else if (segments[1] && root === "tenants") {
    content = <StatePanel state="forbidden" message="TMS 只能访问可信身份绑定的当前学校。"/>;
  } else if (root === "home") {
    const tasks = [
      { id: "t-1", task: "文档 OCR 额度已用尽", context: "新的 OCR 调用暂不可用；登录和管理不受影响", status: "需关注", path: `${base}/quotas/q-103` },
      { id: "t-2", task: "历史试题归档索引失败", context: "查看知识库详情与处理记录", status: "待处理", path: `${base}/knowledge/kb-03` },
      { id: "t-3", task: "一条模型用量待核对", context: "未知用量不显示为零", status: "待核对", path: `${base}/usage/use-7422` },
    ];
    content = <><PageHead eyebrow="学校概览" title="工作台" description={`${tenant.name} · 学校状态来自 ${tenant.source}，最近同步 ${tenant.synced}`} actions={<div className="scenario-bar"><label htmlFor="scenario">审计场景</label><select id="scenario" value={scenario} onChange={e => setScenario(e.target.value)}><option value="normal">正常</option><option value="loading">加载中</option><option value="empty">空记录</option><option value="error">读取失败</option><option value="forbidden">无权限</option></select></div>}/>
      <MetricStrip items={[{ label: "成员", value: `${members.length}`, note: "当前学校演示数据" }, { label: "应用", value: `${apps.length}`, note: "本学校归口" }, { label: "可用服务", value: `${services.length}`, note: "由 OMS 授权" }, { label: "待处理事项", value: "3", note: "配额、知识与用量", tone: "warning" }]}/>
      <Section title="待处理事项" subtitle="只展示当前学校需要关注的记录"><DataTable rows={viewState === "empty" ? [] : tasks} state={viewState} searchLabel="搜索事项" onOpen={row => go(row.path)} columns={[{ key: "task", label: "事项", render: row => title(row.task, row.context) }, { key: "status", label: "状态", render: row => badge(row.status) }]}/></Section><div className="audit-note">演示环境不接入真实身份、额度、知识库或调用总账。</div></>;
  } else if (root === "members") {
    const member = members.find(item => item.id === segments[1]);
    const memberView = segments[2] ?? "info";
    const grantableApps = eligibleApps.filter(item => !(memberAccess[member?.id ?? ""] ?? []).includes(item.id));
    content = member ? <><PageHead eyebrow="成员详情" title={member.name} breadcrumbs={crumbs("成员与权限", `${base}/members`, member.name)} description="合成成员按 EduPlus2 身份字段展示；TMS 仅演练本校资源访问关系。"/>
      {memberView === "info" && <><DetailGrid rows={[{ label: "人员类别", value: member.identity }, { label: "部门", value: member.department }, { label: "演示状态", value: badge(member.status) }, { label: "身份来源", value: member.source }, { label: "当前学校", value: tenant.name }]}/><Button onClick={() => go(`${base}/usage?member=${encodeURIComponent(member.id)}`)}>查看成员调用</Button></>}
      {memberView === "roles" && <TmsMemberRoles memberId={member.id} state={authState} onChange={setAuthState} role={role} onModalChange={setAuthModalOpen}/>}
      {memberView === "services" && <Section title="经应用可用服务"><Notice>仅从已登记的成员—应用与应用—服务关系推导，不代表个人直接获得 OMS 服务授权，也不包含额度。</Notice><ServiceList services={services.filter(service => (memberAccess[member.id] ?? []).some(appId => (serviceAccess[appId] ?? []).includes(service.id)))} showHeading={false} rowActions={row => [{ label: "服务资料", onClick: () => go(`${base}/services/${row.id}/info`) }]}/></Section>}
      {memberView === "resources" && <Section title="共享资源"><Notice tone="warn">当前没有可信的共享资源个人 grant 来源；不能按学校角色或全校知识库推断成员可读私有正文。</Notice></Section>}
      {memberView === "access" && <><div className="section-head"><h2>应用访问</h2><Button onClick={() => { setMessage(""); setAccessApp(grantableApps[0]?.id ?? ""); setFormOpen(!formOpen); }} disabled={member.status !== "正常" || grantableApps.length === 0}>授予应用访问（演示）</Button></div>{formOpen && <FormModal title="授予应用访问" onClose={() => setFormOpen(false)} suspended={!!accessConfirmation}><div className="side-panel"><Notice>只能在 OMS 已授权的服务范围内安排访问，不能调整配额总量或余额。</Notice><label className="form-field">应用<select value={accessApp} onChange={e => setAccessApp(e.target.value)}>{grantableApps.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{formOpen && message && <Notice tone="bad">{message}</Notice>}<div className="form-actions"><Button variant="primary" onClick={() => { if (member.status !== "正常" || !grantableApps.some(item => item.id === accessApp)) { setMessage("成员身份须已核验，且只能授权使用 OMS 获授权服务的应用。"); return; } setAccessConfirmation({ memberId: member.id, appId: accessApp, action: "grant" }); }}>确认演示授权</Button><Button onClick={() => setFormOpen(false)}>取消</Button></div></div></FormModal>}{!formOpen && message && <Notice>{message}</Notice>}<DataTable rows={apps.filter(item => (memberAccess[member.id] ?? []).includes(item.id))} searchLabel="搜索应用" rowActions={row => [{ label: "查看应用", onClick: () => go(`${base}/apps/${row.id}/info`) }, { label: "撤销访问", onClick: () => setAccessConfirmation({ memberId: member.id, appId: row.id, action: "revoke" }) }]} columns={[{ key: "name", label: "应用", render: row => row.name }, { key: "status", label: "状态", render: row => badge(row.status) }]}/></>}

      </> : <><PageHead eyebrow="成员与权限" title="成员与权限" description="当前学校的合成可见成员；目录查询与角色授权分开，不修改外部身份。" actions={role === "admin" ? <Button onClick={() => setDirectoryOpen(true)}>查找本校账号</Button> : undefined}/><Section><DataTable rows={viewState === "empty" ? [] : members} state={viewState} searchLabel="搜索成员" persistKey={`tms:${schoolCode}:members`} rowActions={row => [{ label: "成员资料", onClick: () => go(`${base}/members/${row.id}/info`) }, { label: "学校角色", onClick: () => go(`${base}/members/${row.id}/roles`) }, { label: "应用访问", onClick: () => go(`${base}/members/${row.id}/access`) }, { label: "服务访问", onClick: () => go(`${base}/members/${row.id}/services`) }, { label: "共享资源", onClick: () => go(`${base}/members/${row.id}/resources`) }]} columns={[{ key: "name", label: "成员", render: row => title(row.name, row.department) }, { key: "identity", label: "人员类别", render: row => row.identity }, { key: "source", label: "来源", render: row => row.source }, { key: "status", label: "状态", render: row => badge(row.status) }]}/></Section></>;
  } else if (root === "apps") {
    const app = apps.find(item => item.id === segments[1]);
    const appView = segments[2] ?? "info";
    content = app ? <><PageHead eyebrow="应用详情" title={app.name} breadcrumbs={crumbs("应用与接入", `${base}/apps`, app.name)} description="应用接入与成员访问属于当前学校；平台服务范围由 OMS 决定。"/>
      {appView === "info" && <><DetailGrid rows={[{ label: "应用归口", value: app.owner }, { label: "状态", value: badge(app.status) }, { label: "学校", value: tenant.name }]}/><Button onClick={() => go(`${base}/usage?app=${encodeURIComponent(app.id)}`)}>查看应用调用</Button></>}
      {appView === "connection" && app.id === "app-04" && <Notice tone="warn">EduPlus2 client 归口尚未与当前学校匹配。此应用不能激活接入或调用服务，且不会显示其他学校的信息。</Notice>}
      {appView === "services" && <Section action={role === "admin" && app.status !== "归口待核对" ? <Button onClick={() => { setServiceChoice(services.find(row => !(serviceAccess[app.id] ?? []).includes(row.id))?.id ?? ""); setMessage(""); setServiceFormOpen(true); }}>添加服务</Button> : undefined}><ServiceList services={services.filter(row => (serviceAccess[app.id] ?? []).includes(row.id))} showHeading={false} rowActions={row => [{ label: "服务资料", onClick: () => go(`${base}/services/${row.id}/info`) }, ...(role === "admin" ? [{ label: "移除服务", onClick: () => setServiceConfirmation({ appId: app.id, serviceId: row.id, action: "remove" as const }) }] : [])]}/></Section>}
      {appView === "services" && serviceFormOpen && <FormModal title="添加应用服务" onClose={() => setServiceFormOpen(false)} suspended={!!serviceConfirmation}><div className="side-panel"><Notice>只能选择 OMS 已授权给本学校的服务；这不修改学校配额。</Notice><label className="form-field">服务<select value={serviceChoice} onChange={event => { setServiceChoice(event.target.value); setMessage(""); }}>{services.filter(row => !(serviceAccess[app.id] ?? []).includes(row.id)).map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label>{message && <Notice tone="bad">{message}</Notice>}<div className="form-actions"><Button variant="primary" onClick={() => { if (!services.some(row => row.id === serviceChoice) || (serviceAccess[app.id] ?? []).includes(serviceChoice) || app.status === "归口待核对") { setMessage("该服务不可加入当前应用。"); return; } setServiceConfirmation({ appId: app.id, serviceId: serviceChoice, action: "add" }); }}>提交添加</Button><Button onClick={() => setServiceFormOpen(false)}>取消</Button></div></div></FormModal>}
      {appView === "members" && <Section action={role === "admin" && eligibleApps.some(row => row.id === app.id) ? <Button onClick={() => { setMemberChoice(members.find(row => row.status === "正常" && !(memberAccess[row.id] ?? []).includes(app.id))?.id ?? ""); setMessage(""); setAppMemberFormOpen(true); }}>授予成员访问</Button> : undefined}><DataTable rows={members.filter(item => (memberAccess[item.id] ?? []).includes(app.id))} searchLabel="搜索成员" rowActions={row => [{ label: "成员资料", onClick: () => go(`${base}/members/${row.id}/info`) }, ...(role === "admin" ? [{ label: "撤销访问", onClick: () => setAccessConfirmation({ memberId: row.id, appId: app.id, action: "revoke" as const }) }] : [])]} columns={[{ key: "name", label: "成员", render: row => row.name }, { key: "identity", label: "人员类别", render: row => row.identity }]}/></Section>}
      {appView === "members" && appMemberFormOpen && <FormModal title="授予成员访问" onClose={() => setAppMemberFormOpen(false)} suspended={!!accessConfirmation}><div className="side-panel"><label className="form-field">成员<select value={memberChoice} onChange={event => { setMemberChoice(event.target.value); setMessage(""); }}>{members.filter(row => row.status === "正常" && !(memberAccess[row.id] ?? []).includes(app.id)).map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label>{message && <Notice tone="bad">{message}</Notice>}<div className="form-actions"><Button variant="primary" onClick={() => { if (!members.some(row => row.id === memberChoice && row.status === "正常") || (memberAccess[memberChoice] ?? []).includes(app.id) || !eligibleApps.some(row => row.id === app.id)) { setMessage("当前成员或应用不具备可授予条件。"); return; } setAccessConfirmation({ memberId: memberChoice, appId: app.id, action: "grant" }); }}>提交授权</Button><Button onClick={() => setAppMemberFormOpen(false)}>取消</Button></div></div></FormModal>}
      {appView === "connection" && <DetailGrid rows={[{ label: "应用标识", value: app.id }, { label: "归口部门", value: app.owner }, { label: "外部身份来源", value: "EduPlus2" }, { label: "归口校验", value: app.id === "app-04" ? badge("待核对") : badge("正常") }, { label: "当前学校", value: tenant.name }, { label: "密钥", value: "不在演示界面展示" }]}/>}

      </> : <><PageHead eyebrow="应用与接入" title="应用与接入" description="在本学校范围内管理应用归口与访问；不自行扩大服务配额。" actions={role === "admin" ? <Button variant="primary" onClick={() => { setMessage(""); setFormOpen(!formOpen); }}>新增应用（演示）</Button> : undefined}/>
        {formOpen && <FormModal title="新增应用" onClose={() => setFormOpen(false)}><div className="side-panel"><Notice>仅修改当前页面本地数据，不向 EduPlus2 或基座发送请求。</Notice><div className="form-grid"><label className="form-field">应用名称<input value={appName} onChange={e => setAppName(e.target.value)} placeholder="例如：教研助手"/></label><label className="form-field">归口部门<select value={appOwner} onChange={event => setAppOwner(event.target.value)}><option>教务处</option><option>数学教研组</option></select></label></div>{formOpen && message && <Notice tone="bad">{message}</Notice>}<div className="form-actions"><Button variant="primary" onClick={() => { if (appName.trim().length < 2) { setMessage("应用名称至少需要 2 个字符。"); return; } setApps([...apps, { id: `app-demo-${Date.now()}`, name: appName.trim(), owner: appOwner, status: "待接入", last: "尚无调用" }]); setAppName(""); setFormOpen(false); setMessage("演示应用已加入当前学校列表；未创建真实 client。" ); }}>保存演示应用</Button><Button onClick={() => setFormOpen(false)}>取消</Button></div></div></FormModal>}{!formOpen && message && <Notice>{message}</Notice>}
        <Section><DataTable rows={viewState === "empty" ? [] : apps} state={viewState} searchLabel="搜索应用" persistKey={`tms:${schoolCode}:apps`} rowActions={row => [{ label: "应用资料", onClick: () => go(`${base}/apps/${row.id}/info`) }, { label: "服务范围", onClick: () => go(`${base}/apps/${row.id}/services`) }, { label: "成员访问", onClick: () => go(`${base}/apps/${row.id}/members`) }, { label: "接入状态", onClick: () => go(`${base}/apps/${row.id}/connection`) }]} columns={[{ key: "name", label: "应用", render: row => title(row.name, row.owner) }, { key: "services", label: "可用服务", render: row => services.filter(item => (serviceAccess[row.id] ?? []).includes(item.id)).map(item => item.name).join("、") || "未分配" }, { key: "last", label: "最近调用", render: row => row.last }, { key: "status", label: "状态", render: row => badge(row.status) }]}/></Section></>;
  } else if (root === "skills") {
    content = <TmsSkills schoolCode={schoolCode} selectedId={skillId} view={segments[2] ?? "info"} onOpen={(id, view) => go(`${base}/skills/${encodeURIComponent(id)}/${view}`)} onClose={() => go(`${base}/skills`)} state={viewState}/>;
  } else if (root === "services") {
    const service = services.find(item => item.id === segments[1]);
    const serviceView = segments[2] ?? "info";
    content = service ? <><PageHead eyebrow="服务详情" title={service.name} breadcrumbs={crumbs("可用服务", `${base}/services`, service.name)} description="只显示本学校获授权服务；服务配置由 OMS 维护。"/>{serviceView === "info" && <><ServiceDetail service={service}/><Button onClick={() => go(`${base}/usage?service=${encodeURIComponent(service.id)}`)}>查看服务调用</Button></>}
      {serviceView === "info" && service.id === "ocr" && <Notice tone="warn">文档 OCR 赠送额度已用尽；仅此服务的新调用受限，登录、管理和其他服务仍可使用。</Notice>}
      {serviceView === "quotas" && <DataTable rows={grants.filter(g => g.serviceId === service.id)} searchLabel="搜索配额" rowActions={row => [{ label: "查看配额", onClick: () => go(`${base}/quotas/${row.id}`) }, { label: "消耗明细", onClick: () => go(`${base}/usage?grant=${encodeURIComponent(row.id)}`) }]} columns={[{ key: "id", label: "配额记录", render: row => title(row.id, row.method) }, { key: "remaining", label: "剩余", render: row => `${row.remaining} ${row.unit}` }, { key: "status", label: "状态", render: row => badge(row.status) }]}/>}
      {serviceView === "apps" && <DataTable rows={apps.filter(row => (serviceAccess[row.id] ?? []).includes(service.id))} searchLabel="搜索应用" rowActions={row => [{ label: "应用资料", onClick: () => go(`${base}/apps/${row.id}/info`) }, { label: "管理服务范围", onClick: () => go(`${base}/apps/${row.id}/services`) }]} columns={[{ key: "name", label: "应用", render: row => row.name }, { key: "owner", label: "归口", render: row => row.owner }]}/>}

      </> : <><PageHead eyebrow="可用服务" title="可用服务" description="按 OMS 授权范围查看模型、Agent、工具与知识处理服务。"/><Tabs tabs={["全部服务", "文档识别与解析"]} active={catalogTab} onChange={setCatalogTab}/>{catalogTab === "全部服务" ? <ServiceList services={viewState === "empty" ? [] : services} state={viewState} showHeading={false} rowActions={row => [{ label: "服务资料", onClick: () => go(`${base}/services/${row.id}/info`) }, { label: "关联配额", onClick: () => go(`${base}/services/${row.id}/quotas`) }, { label: "使用应用", onClick: () => go(`${base}/services/${row.id}/apps`) }]}/> : <OcrServiceList services={services.filter(item => item.category === "知识处理")} state={viewState} showHeading={false} rowActions={row => [{ label: "服务资料", onClick: () => go(`${base}/services/${row.id}/info`) }, { label: "关联配额", onClick: () => go(`${base}/services/${row.id}/quotas`) }, { label: "使用应用", onClick: () => go(`${base}/services/${row.id}/apps`) }]}/>}</>;
  } else if (root === "quotas") {
    const quota = grants.find(item => item.id === segments[1]);
    content = quota ? <><PageHead eyebrow="配额详情 · 只读" title={`配额 ${quota.id}`} breadcrumbs={crumbs("配额清单", `${base}/quotas`, quota.id)} description="由 OMS 配置与授予；这里仅可查看。"/>
      <DetailGrid rows={[{ label: "服务", value: quota.service }, { label: "获取方式", value: quota.method }, { label: "状态", value: badge(quota.status) }, { label: "授予总量", value: `${quota.total} ${quota.unit}` }, { label: "已消耗", value: `${quota.used} ${quota.unit}` }, { label: "剩余额度", value: `${quota.remaining} ${quota.unit}` }, { label: "有效期", value: quota.valid }, { label: "授予方", value: "OMS 平台运营" }, { label: "所属学校", value: tenant.name }]}/>
      <Notice>配额创建、赠送、充值、调整和撤销均只能由 OMS 完成。当前页面没有任何配额写入能力。</Notice>
      <Section title="关联服务"><DataTable rows={services.filter(row => row.id === quota.serviceId)} searchLabel="搜索关联服务" rowActions={row => [{ label: "服务资料", onClick: () => go(`${base}/services/${row.id}/info`) }, { label: "该服务配额", onClick: () => go(`${base}/services/${row.id}/quotas`) }]} columns={[{ key: "name", label: "服务", render: row => row.name }]}/></Section>
      <Button onClick={() => go(`${base}/usage?grant=${encodeURIComponent(quota.id)}`)}>查看消耗明细</Button></> : <><PageHead eyebrow="配额清单 · 只读" title="配额清单" description="同一清单展示赠送与充值；额度由 OMS 授予，您只能查询。"/><Notice>配额用尽只限制对应服务的新调用，登录、管理和其他服务不受影响。</Notice>
        <Section><DataTable rows={viewState === "empty" ? [] : grants.filter(q => method === "all" || q.method === method)} searchLabel="搜索配额" persistKey={`tms:${schoolCode}:quotas`} state={viewState} filters={[{ label: "获取方式", value: method, onChange: setMethod, options: [{ label: "全部方式", value: "all" }, { label: "赠送", value: "赠送" }, { label: "充值", value: "充值" }] }]} onOpen={row => go(`${base}/quotas/${row.id}`)} columns={[{ key: "service", label: "服务", render: row => title(row.service, row.id) }, { key: "method", label: "获取方式", render: row => row.method }, { key: "remaining", label: "剩余", render: row => `${row.remaining} ${row.unit}` }, { key: "valid", label: "有效期", render: row => row.valid }, { key: "status", label: "状态", render: row => badge(row.status) }]}/></Section></>;
  } else if (root === "knowledge") {
    const kb = knowledge.find(item => item.id === segments[1]);
    const knowledgeView = segments[2] ?? "info";
    const document = knowledgeView === "documents" && segments[3] ? documents.find(row => row.kbId === kb?.id && row.id === segments[3]) : undefined;
    const task = knowledgeView === "tasks" && segments[3] ? processingTasks.find(row => row.kbId === kb?.id && row.id === segments[3]) : undefined;
    content = kb ? <><PageHead eyebrow="知识库详情" title={document?.name ?? task?.name ?? kb.name} breadcrumbs={crumbs("知识与内容", `${base}/knowledge`, kb.name)} description="学校知识资源的归属、文档与索引状态。"/>{knowledgeView === "info" && <DetailGrid rows={[{ label: "归口", value: kb.owner }, { label: "文档数量", value: kb.files }, { label: "索引状态", value: badge(kb.index) }, { label: "最近更新", value: kb.updated }, { label: "所属学校", value: tenant.name }, { label: "正文访问", value: "仅资源 owner / 获授权成员" }]}/>}
      {knowledgeView === "tasks" && kb.index === "索引失败" && <Notice tone="bad">该知识库索引失败，需要资源管理员检查文档处理任务；其他知识库仍可使用。</Notice>}
      {knowledgeView === "documents" && document && <><DetailGrid rows={[{ label: "文档", value: document.name }, { label: "归口", value: document.owner }, { label: "处理状态", value: badge(document.status) }, { label: "最近更新", value: document.updated }, { label: "所属知识库", value: kb.name }]}/><Notice>仅显示演示文档元数据；不加载私有文件正文或下载链接。</Notice></>}
      {knowledgeView === "documents" && !segments[3] && <><Notice>仅显示演示文档元数据，不加载私有文件正文或下载链接。</Notice><DataTable rows={documents.filter(item => item.kbId === kb.id)} searchLabel="搜索文档" rowActions={row => [{ label: "文档资料", onClick: () => go(`${base}/knowledge/${kb.id}/documents/${row.id}`) }]} columns={[{ key: "name", label: "文档", render: row => title(row.name, row.id) }, { key: "owner", label: "归口", render: row => row.owner }, { key: "status", label: "状态", render: row => badge(row.status) }, { key: "updated", label: "更新", render: row => row.updated }]}/></>}
      {knowledgeView === "tasks" && task && <><DetailGrid rows={[{ label: "任务", value: task.name }, { label: "处理状态", value: badge(retryRequests.includes(task.id) ? "已登记重试申请" : task.status) }, { label: "最近更新", value: task.updated }, { label: "所属知识库", value: kb.name }]}/>{task.status === "失败" && role === "admin" && <Button onClick={() => setRetryConfirmation(task.id)}>申请重试</Button>}{message && <Notice>{message}</Notice>}</>}
      {knowledgeView === "tasks" && !segments[3] && <><DataTable rows={processingTasks.filter(item => item.kbId === kb.id)} searchLabel="搜索任务" rowActions={row => [{ label: "任务状态", onClick: () => go(`${base}/knowledge/${kb.id}/tasks/${row.id}`) }, ...(row.status === "失败" && role === "admin" ? [{ label: "申请重试", onClick: () => setRetryConfirmation(row.id) }] : [])]} columns={[{ key: "name", label: "任务", render: row => title(row.name, row.id) }, { key: "status", label: "状态", render: row => badge(retryRequests.includes(row.id) ? "已登记重试申请" : row.status) }, { key: "updated", label: "更新", render: row => row.updated }]}/>{message && <Notice>{message}</Notice>}</>}
      {knowledgeView === "access" && <Notice tone="warn">访问关系待接入可信授权来源；不展示推测的成员权限。</Notice>}
      </> : <><PageHead eyebrow="知识与内容" title="知识与内容" description="按知识库查看文档、索引与处理状态；私有正文受 owner/grant 保护。"/><Section><DataTable rows={viewState === "empty" ? [] : knowledge} state={viewState} searchLabel="搜索知识库" persistKey={`tms:${schoolCode}:knowledge`} rowActions={row => [{ label: "知识库资料", onClick: () => go(`${base}/knowledge/${row.id}/info`) }, { label: "文档清单", onClick: () => go(`${base}/knowledge/${row.id}/documents`) }, { label: "处理任务", onClick: () => go(`${base}/knowledge/${row.id}/tasks`) }, { label: "访问范围", onClick: () => go(`${base}/knowledge/${row.id}/access`) }]} columns={[{ key: "name", label: "知识库", render: row => title(row.name, row.owner) }, { key: "files", label: "文档", render: row => row.files }, { key: "index", label: "索引状态", render: row => badge(row.index) }, { key: "updated", label: "更新", render: row => row.updated }]}/></Section></>;
  } else if (root === "usage") {
    const call = calls.find(item => item.id === segments[1]);
    content = call ? <><PageHead eyebrow="用量详情" title={`调用 ${call.id}`} breadcrumbs={crumbs("用量与记录", `${base}/usage`, call.id)} description="仅查看当前学校获授权的实际消耗记录。"/><DetailGrid rows={[{ label: "时间", value: call.time }, { label: "成员", value: call.member }, { label: "应用", value: call.app }, { label: "服务", value: call.service }, { label: "实际用量", value: call.usage }, { label: "状态", value: badge(call.status) }, { label: "额度消耗", value: call.grant }, { label: "所属学校", value: tenant.name }, { label: "记录来源", value: "演示调用" }]}/><Section title="关联对象"><div className="inline-list"><Button onClick={() => go(`${base}/members/${call.memberId}/info`)}>成员资料</Button><Button onClick={() => go(`${base}/apps/${call.appId}/info`)}>应用资料</Button><Button onClick={() => go(`${base}/services/${call.serviceId}/info`)}>服务资料</Button>{call.grantIds.map(id => grants.some(row => row.id === id && row.serviceId === call.serviceId) ? <Button key={id} onClick={() => go(`${base}/quotas/${id}`)}>配额 {id}</Button> : null)}</div></Section>{call.status === "待核对" && <Notice tone="warn">真实用量尚未确认，不能将该调用记作零。</Notice>}</> : <><PageHead eyebrow="用量与记录" title="用量与记录" description="从服务、应用或成员逐级查看单次调用；不展示其他学校。"/>{list(calls.filter(row => { const query = new URLSearchParams(locationSearch); return (!query.get("grant") || row.grantIds.includes(query.get("grant")!)) && (!query.get("service") || row.serviceId === query.get("service")) && (!query.get("app") || row.appId === query.get("app")) && (!query.get("member") || row.memberId === query.get("member")); }), [{ key: "id", label: "调用", render: row => title(row.id, row.time) }, { key: "member", label: "成员 / 应用", render: row => title(row.member, row.app) }, { key: "service", label: "服务", render: row => row.service }, { key: "usage", label: "实际用量", render: row => row.usage }, { key: "status", label: "状态", render: row => badge(row.status) }], row => `${base}/usage/${row.id}`, "搜索用量")}</>;
  } else if (root === "events") {
    const event = events.find(item => item.id === segments[1]);
    content = event ? <><PageHead eyebrow="事件详情" title={event.action} breadcrumbs={crumbs("管理事件", `${base}/events`, event.id)}/><DetailGrid rows={[{ label: "事件编号", value: event.id }, { label: "时间", value: event.time }, { label: "操作者", value: event.actor }, { label: "目标", value: event.target }, { label: "状态", value: badge(event.status) }, { label: "所属学校", value: tenant.name }]}/></> : <><PageHead eyebrow="学校管理事件" title="管理事件" description="当前学校的应用、授权与知识资源操作记录。"/>{list(events, [{ key: "action", label: "事件", render: row => title(row.action, row.id) }, { key: "target", label: "目标", render: row => row.target }, { key: "actor", label: "操作者", render: row => row.actor }, { key: "time", label: "时间", render: row => row.time }], row => `${base}/events/${row.id}`, "搜索事件")}</>;
  } else { content = <StatePanel state="empty" message="该原型页面不存在。"/>; }
  return content;
  };

  // 演示路由也不允许通过猜测 ID 或追加写入路径读取越界对象。
  const allowedIds: Record<string, string[]> = {
    members: members.map(item => item.id), apps: apps.map(item => item.id), services: services.map(item => item.id),
    quotas: grants.map(item => item.id), knowledge: knowledge.map(item => item.id), usage: calls.map(item => item.id), events: events.map(item => item.id),
  };
  const allowedViews: Record<string, string[]> = { members: ["info", "roles", "access", "services", "resources"], apps: ["info", "services", "members", "connection"], services: ["info", "quotas", "apps"], knowledge: ["info", "documents", "tasks", "access"], quotas: [], usage: [], events: [], skills: ["info", "package", "release"] };
  const deniedKnowledgeRecord = !!segments[3] && !(root === "knowledge" && ((segments[2] === "documents" && documents.some(row => row.kbId === segments[1] && row.id === segments[3])) || (segments[2] === "tasks" && processingTasks.some(row => row.kbId === segments[1] && row.id === segments[3]))));
  const deniedTarget = !inSchoolScope || root === "tenants" || segments.length > 4 || deniedKnowledgeRecord || (root === "skills" && !!segments[1] && !skillId) || (segments[1] && root !== "skills" && !authRoots.has(root) && !allowedIds[root]?.includes(segments[1])) || (!!segments[2] && !authRoots.has(root) && !allowedViews[root]?.includes(segments[2]));
  const isDetail = segments.length > 1 && root !== "skills" && !authRoots.has(root);
  const detailName = root === "members" ? members.find(row => row.id === segments[1])?.name
    : root === "apps" ? apps.find(row => row.id === segments[1])?.name
    : root === "services" ? services.find(row => row.id === segments[1])?.name
    : root === "quotas" ? `配额 ${segments[1]}`
    : root === "knowledge" ? (segments[2] === "documents" && segments[3] ? documents.find(row => row.kbId === segments[1] && row.id === segments[3])?.name : segments[2] === "tasks" && segments[3] ? processingTasks.find(row => row.kbId === segments[1] && row.id === segments[3])?.name : knowledge.find(row => row.id === segments[1])?.name)
    : root === "usage" ? `调用 ${segments[1]}`
    : root === "events" ? events.find(row => row.id === segments[1])?.action : undefined;
  const listContent = renderContent(isDetail ? [root] : segments);
  const detailContent = isDetail ? renderContent(segments) : null;

  const hasSchoolAdmin = authState.assignments.some(item => item.roleId === "school-admin" && item.status.startsWith("有效"));
  const effectiveAuthScenario = authScenario === "active" && !hasSchoolAdmin ? "bootstrap-pending" : authScenario;
  const authBlocked = effectiveAuthScenario !== "active";
  const authMessage: Record<string, { title: string; detail: string }> = { "bootstrap-pending": { title: "等待订阅 Webhook", detail: "学校管理员无需单独开通；未接收到有效 subscription.created 前保持零权。此处仅合成演示。" }, "not-authorized": { title: "学校后台待开通", detail: "当前主体已完成学校登录，但尚未获得本产品管理授权。" }, revoked: { title: "管理授权已撤销", detail: "旧页面的管理动作已失效；请联系本校管理员，不能重放旧请求。" }, expired: { title: "管理授权已过期", detail: "角色有效期已结束，当前不能管理学校资源。" }, paused: { title: "学校已暂停", detail: "学校 lifecycle 由 EduPlus2 权威确认；管理写入暂不可用。" }, "external-error": { title: "外部核验暂不可用", detail: "账号在线状态或学校绑定未获确认，敏感管理操作失败关闭。" } };
  return <AdminShell product="TMS" subtitle="学校智能体管理后台" scope={`${tenant.name} · ${schoolCode}`} groups={role === "member" || authBlocked ? nav.slice(0, 1) : nav} path={root === "home" ? base : `${base}/${root}`} onNavigate={path => { setFormOpen(false); setMessage(""); go(path); }}>
    <div className="scenario-bar role-scenario-bar" style={{ justifyContent: "flex-end", marginBottom: 12 }}><span>演示角色</span><select aria-label="演示角色" value={role} onChange={e => { setDirectoryOpen(false); setRole(e.target.value); }}><option value="admin">学校管理员</option><option value="member">普通成员</option></select><span>演示权限状态</span><select aria-label="演示权限状态" value={effectiveAuthScenario} onChange={e => { const next = e.target.value; setDirectoryOpen(false); if (next === "bootstrap-pending") setAuthState(current => ({ ...current, assignments: current.assignments.filter(item => item.roleId !== "school-admin"), audits: [] })); setAuthScenario(next === "active" && !hasSchoolAdmin ? "bootstrap-pending" : next); }}><option value="active">已授权</option><option value="not-authorized">待授权</option><option value="bootstrap-pending">等待订阅 Webhook</option><option value="expired">已过期</option><option value="revoked">已撤权</option><option value="paused">学校停用</option><option value="external-error">外部核验失败</option></select></div>
    {authBlocked ? <><PageHead eyebrow="本产品管理权限 · 合成演示" title={authMessage[effectiveAuthScenario].title}/><Notice tone="warn">{authMessage[effectiveAuthScenario].detail}</Notice><Notice>只展示当前学校必要的开通状态，不读取成员、应用或配额业务数据；此处不接真实授权 API。</Notice>{effectiveAuthScenario === "bootstrap-pending" && <TmsSchoolActivation onActivated={() => { setAuthState(current => ({ ...current, assignments: [...current.assignments, initialTmsAuth.assignments[0]], audits: [...current.audits, { id: `t-authz-${current.audits.length + 1}`, action: "订阅 Webhook 即时开启学校管理员", target: "本校首位管理员", actor: "事件 actor（合成演示）", reason: "真实订阅事件 actor 已验签（仅演示）", status: "演示记录" }] })); setAuthScenario("active"); }}/>}</> : viewState === "forbidden" || deniedTarget ? <StatePanel state="forbidden" message="当前主体不能访问该学校管理资源或写入路径。"/> : <>{listContent}{isDetail && <Drawer title={`详情 · ${detailName ?? "未找到"}`} onClose={() => { setFormOpen(false); if (root === "knowledge" && segments[3]) { go(`${base}/knowledge/${segments[1]}/${segments[2]}`, true); return; } if (returnRoute) { const previous = returnRoute; setReturnRoute(null); go(previous, true); } else go(`${base}/${root}`); }} suspended={formOpen || serviceFormOpen || appMemberFormOpen || authModalOpen || !!accessConfirmation || !!serviceConfirmation || !!retryConfirmation}>{detailContent}</Drawer>}</>}
    {directoryOpen && root === "members" && !segments[1] && !authBlocked && role === "admin" && <TmsMemberLookup onClose={() => setDirectoryOpen(false)} onOpenMember={id => go(`${base}/members/${id}/info`)}/>}
    {serviceConfirmation && <ConfirmModal title={serviceConfirmation.action === "add" ? "确认添加应用服务" : "确认移除应用服务"} description={`${apps.find(row => row.id === serviceConfirmation.appId)?.name ?? serviceConfirmation.appId} · ${services.find(row => row.id === serviceConfirmation.serviceId)?.name ?? serviceConfirmation.serviceId}；仅更新本学校演示服务范围，不修改 OMS 授权或额度。`} onCancel={() => setServiceConfirmation(null)} onConfirm={() => { const { appId, serviceId, action } = serviceConfirmation; if (action === "add" && (!services.some(row => row.id === serviceId) || !apps.some(row => row.id === appId && row.status !== "归口待核对"))) { setServiceConfirmation(null); return; } setServiceAccess(current => ({ ...current, [appId]: action === "add" ? [...new Set([...(current[appId] ?? []), serviceId])] : (current[appId] ?? []).filter(id => id !== serviceId) })); setServiceConfirmation(null); setServiceFormOpen(false); setMessage(action === "add" ? "演示服务范围已更新。" : "演示服务范围已移除。"); }}/ >}
    {retryConfirmation && <ConfirmModal title="确认登记重试申请" description={`${processingTasks.find(row => row.id === retryConfirmation)?.name ?? retryConfirmation}；仅登记本地演示申请，不启动处理任务，也不修改索引状态。`} onCancel={() => setRetryConfirmation(null)} onConfirm={() => { setRetryRequests(current => [...new Set([...current, retryConfirmation])]); setRetryConfirmation(null); setMessage("已登记本地重试申请；处理任务尚未执行。"); }}/ >}
    {accessConfirmation && <ConfirmModal title={accessConfirmation.action === "grant" ? "确认授予应用访问" : "确认撤销应用访问"} description={`${members.find(row => row.id === accessConfirmation.memberId)?.name ?? accessConfirmation.memberId} · ${apps.find(row => row.id === accessConfirmation.appId)?.name ?? accessConfirmation.appId}；仅更新本学校演示访问关系。`} onCancel={() => setAccessConfirmation(null)} onConfirm={() => { const { memberId, appId, action } = accessConfirmation; setMemberAccess(current => ({ ...current, [memberId]: action === "grant" ? [...new Set([...(current[memberId] ?? []), appId])] : (current[memberId] ?? []).filter(id => id !== appId) })); setMessage(action === "grant" ? "演示访问关系已更新；未写入真实授权服务。" : "演示访问关系已撤销；真实授权未变更。"); setFormOpen(false); setAppMemberFormOpen(false); setAccessConfirmation(null); }}/>}
  </AdminShell>;
}

export default function TmsPrototype({ schoolCode = "demo-school" }: { schoolCode?: string }) {
  // 切换学校时卸载全部本地草稿和筛选状态，避免复用上一学校的前端实例。
  return <TmsPrototypeForSchool key={schoolCode} schoolCode={schoolCode}/>;
}
